### ISSUE TITLE
about the training set

### ISSUE THREAD

**Issue by DIO-1-2** [cshennju/NeuralCMF#1]
您好，请问训练3d的数据集的话是只能用一个序列吗，在dataset/heart_dy_3d.py里看到read_meta函数里的代码这部分是
self.image_paths = glob.glob(os.path.join(self.root_dir, '*'))
data = np.load(self.image_paths[0])

谢谢

**Comment by cshennju** [comment]
对的，训练数据集是一个序列的volume，训练完成后可以得到volume上每个点的三维运动。
