### ISSUE TITLE
关于测试

### ISSUE THREAD

**Issue by DIO-1-2** [cshennju/NeuralCMF#2]
您好，我想问一下训练完成后该如何测试，是取序列中的一帧图像的所有点，将时间t设为0测试吗，这样测试出来的结果比较平滑，谢谢
<img width="304" alt="图片1" src="https://github.com/cshennju/NeuralCMF/assets/81473526/0c8fd78a-4193-4c84-9f52-cddc0b70b16e">

**Comment by cshennju** [comment]
你好感谢关注！
在训练完成后，如果想得到某一时刻的三维心脏图像，则需要输入三维空间中每个点的坐标和相应的时间T，模型将输出对应的灰度值。如果想追踪目标点或区域运动的位移，则首先在第一帧选择感兴趣区域（比如论文中选择的心肌区域），得到区域内每一点的三维坐标值，然后输入网络，得到相应的forward motion，连接每一帧的forward motion就可得到运动轨迹。
我这两天会上传我的测试代码，还有示例数据给你参考。




发自我的iPhone


------------------ 原始邮件 ------------------
发件人: DIO-1-2 ***@***.***&gt;
发送时间: 2023年12月22日 19:52
收件人: cshennju/NeuralCMF ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [cshennju/NeuralCMF] 关于测试 (Issue #2)





 
您好，我想问一下训练完成后该如何测试，是取序列中的一帧图像的所有点，将时间t设为0测试吗，这样测试出来的结果比较平滑，谢谢
 1.png (view on web)

**Comment by DIO-1-2** [comment]
好的，非常感谢您！

**Comment by cshennju** [comment]
你好，我更新上去了。

vis_3d.py 是可视化三维成像结果的示例代码。 


test_tj_straus.py 是提取运动信息的示例代码（提取三维volume中每一点的位移，后续你可以根据需要只保留或可视化部分需要的区域）


 

&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Sat, Dec 23, 2023 12:47 PM
To: ***@***.***&gt;; 
Cc: &nbsp;"Chengkang ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [cshennju/NeuralCMF] 关于测试 (Issue #2)

&nbsp;



 
好的，非常感谢您！

**Comment by DIO-1-2** [comment]
您好，感谢您的代码。但是我测试以后三维成像的结果依然是平滑的，不太清楚原因。这和训练使用的优化器有关吗，因为apex环境配置出现很多问题，所以我用的adam代替的fusedadam。
![Uploading 图片1.png…]()

**Comment by cshennju** [comment]
你好，关于结果平滑和优化器应该没有关系，你可以尝试多训练一些epochs，让PSNR更高一些来改善平滑问题。目前设置10是权衡运动追踪效果和训练时间后设置的，选择fusedadam则也是为了提升训练速度。
